//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLRCServiceAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DLRCDBEntities : DbContext
    {
        public DLRCDBEntities()
            : base("name=DLRCDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Dl_Review> Tbl_Dl_Review { get; set; }
        public virtual DbSet<Tbl_Ocr> Tbl_Ocr { get; set; }
        public virtual DbSet<Tbl_RC_Endorsement> Tbl_RC_Endorsement { get; set; }
        public virtual DbSet<Tbl_RC_Review> Tbl_RC_Review { get; set; }
        public virtual DbSet<Tbl_DL_Endorsement> Tbl_DL_Endorsement { get; set; }
    }
}
