//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLRCServiceAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_DL_Endorsement
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Dl_Number { get; set; }
        public string Endorsement_Number { get; set; }
        public string Endorsemeent_Date { get; set; }
        public string Authority_id { get; set; }
        public string Rules { get; set; }
        public string Location { get; set; }
        public string Terminal_id { get; set; }
    }
}
