//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLRCServiceAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Ocr
    {
        public int Id { get; set; }
        public string Vehicle_Number { get; set; }
        public string Photo { get; set; }
        public string RegDate { get; set; }
        public string Cof_id { get; set; }
        public string Location { get; set; }
        public string Terminal_id { get; set; }
        public string Rules { get; set; }
    }
}
