//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLRCServiceAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_RC_Endorsement
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Vehicle_Registration_Number { get; set; }
        public string Accused { get; set; }
        public string Rules { get; set; }
        public string Officer_id { get; set; }
        public string Location { get; set; }
        public string Date_Endorsement { get; set; }
        public string Time_Endorsement { get; set; }
        public string Terminal_id { get; set; }
    }
}
