//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLRCServiceAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Dl_Review
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string DL_Number { get; set; }
        public string Fine { get; set; }
        public string Review_Date { get; set; }
        public string Authority_id { get; set; }
        public string Disqualification_Period_from { get; set; }
        public string Disqualification_Period_to { get; set; }
        public string Rules { get; set; }
        public string BackEnd_Update_Flag { get; set; }
        public string Location { get; set; }
        public string Terminal_id { get; set; }
    }
}
